### ISSUE TITLE
How to save the HTML file?

### ISSUE THREAD

**Issue by XiangTodayEatsWhat** [labmlai/inspectus#11]
Hello! Very convenient tool! 
How can I save the HTML file instead of displaying it directly? 
The result of directly saving "html + script" in "attention_chart" function cannot be opened, and the HTML reports an error "window.chartsEmbed is not a functionat output.html".

Thanks!

**Comment by lakshith-403** [comment]
Hello, Thank you for the feedback!

In the `attention_chart` we are only passing data to a function that do the rendering and not providing elements directly. 
You can find the the function here: https://github.com/labmlai/inspectus/blob/main/ui/src/charts.ts

You could inspect and get the html content from the browser if you want to get those separately. At the moment we don't have a method to export content to a standalone file.
