### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by eramax** [labmlai/inspectus#4]
![image](https://github.com/labmlai/inspectus/assets/542413/bff90b67-3ab9-486e-bea0-94cee462aa60)

I ran the same code you shared and got `FileNotFoundError: Could not find the static files for the visualization` and re-run all and got this error.

**Comment by lakshith-403** [comment]
There was an issue on the package and we fixed it. Sorry for the inconvenience. 

About the error on the screenshot, please follow instructions here to run from the source. 
[development docs](https://github.com/labmlai/inspectus/blob/main/development.md)
