### ISSUE TITLE
Resume_download

### ISSUE THREAD

**Issue by byzantinus** [labmlai/inspectus#5]
I get the same error as your example in IPython. How can I resolve this ? Thanks:

/Users/lakshithnishshanke/miniconda3/envs/ML/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

**Comment by lakshith-403** [comment]
This is just a warning. Not an error. Looks like It's due to an internal call in the hugging face library.
