### ISSUE TITLE
Error with Mistral

### ISSUE THREAD

**Issue by SalvatoreRa** [labmlai/inspectus#6]
Hi,

very nice work,  I have tried this notebook:

https://github.com/labmlai/inspectus/blob/main/notebooks/hf_phi.ipynb

While this is working well, I have tried to replicate just changing model:

```
model = AutoModelForCausalLM.from_pretrained(
    "mistralai/Mistral-7B-Instruct-v0.1",
    trust_remote_code=True)

tokenizer = AutoTokenizer.from_pretrained(
    "mistralai/Mistral-7B-Instruct-v0.1",
    trust_remote_code=True)
```

and I encounter this error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[17], line 1
----> 1 attention(res['attentions'], tokens)

TypeError: 'module' object is not callable
```

**Comment by lakshith-403** [comment]
please follow instructions here to run from the source.
[development docs](https://github.com/labmlai/inspectus/blob/main/development.md)

Specifically, you have to install the package.

**Comment by lakshith-403** [comment]
Also if you're just trying out the package It's better to use the pip package. And frequently update it.

```bash
pip install inspectus -U
```

**Comment by SalvatoreRa** [comment]
I have actually installed from pip

I used the same code in the tutorial, just changed the model (for the other model it works great)

**Comment by lakshith-403** [comment]
In that case the issue might have been the existence of an internal module by the same name. We have updated the pip package and the notebooks. Can you try again with the changes?

https://github.com/labmlai/inspectus/commit/b7cb00ea5e5b71e1007bcc2c93e23508794d40a7

**Comment by SalvatoreRa** [comment]
After I have deleted and reinstalled the package it is  working. Thank you!

I see it is an active development, will be implemented new features?

By the way, I am preparing a review about interpretability, I would like to cite your package. How I should cite it?

**Comment by lakshith-403** [comment]
Glad to hear that!
Yes we're planning to continuously add new features.

Please cite the library using the following BibTeX entry.

```bibtext
@misc{inspectus,
 author = {Varuna Jayasiri, Lakshith Nishshanke},
 title = {inspectus: A visualization and analytics tool for large language models},
 year = {2024},
 url = {https://github.com/labmlai/inspectus},
}
```
